language: go
go:
- 1.4.2
env:
- PATH=/home/travis/gopath/bin:$PATH
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
install:
- go get github.com/tools/godep
- godep restore
script:
- "$HOME/gopath/bin/goveralls -service=travis-ci"
deploy:
  provider: heroku
  api_key:
    secure: A968PdjO8eEi6WMBIvx2lxFcKc4hUy0tXEfWcMjKfQ3FEQ23vthnDaeR4p6vvWLXGisxpXCRipC7iTdqJRnZPpF4ADL0m8ayRDzfBwEgzIfugsvttIDsA9b/AvQ2b0ig62WiKFb74zIMIV4mLHSANoqwZE/5hDBC7MFohzxk4Q5bdQC/kHSh+bZt2AvCb9rveGTbehH4yX2K+bVA9ofLggdUtU/ynM4XWxTpVltmZmBSs9s+Ok8tNJcOIfby27haGRsYmy0oB3qLDk181y/MbAFl2orUC0k0H4S+2t6nRGhMcW7SZ/L4+cRQTke4O/Roh11sc7m6FCkiSnsVVQCLqKgPSXLu5WOkvzpbyig9TXNl68l7JSJ++ZecENC8dxl5ys6EeAKMfd+wUd9K+umPXZl8ub1Xp8sowKGXeiczJZ5mPavmgM1Fam7anc0s9Uvng608Nmuh1raJNsgjC6u3wAhEEYj+TFTBCk2YZR+Fr5EJ+HeZ2qJJs1ENRayF/lgBAqbqSoIknlKwt9haBl4B4aoFvCzPx68Tx9B6QkP4RUxW4UYGt/mXcDkD9XG8t8JCHMSIhg5M6rHA+U9znVkivLhXJFBNlg3H7PJXONtOXnAN0Okyacg3UiScCYt37H7VXH7CT3dJ+exFvTq7s0euQDae4rvkPMfM6hakh8FV4+4=
  app: dummy-go-webapp
  on:
    repo: DO-HW/dummy-go-webapp
