language: go

go:
  - 1.4.2

env: 
  - PATH=/home/travis/gopath/bin:$PATH

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go get github.com/tools/godep
  - godep restore

script:
  - $HOME/gopath/bin/goveralls -service=travis-ci
